@startuml LordOfTheRings

package com.lordoftherings{
    class LordOfTheRings{
        -Army heroeArmy
        -Army beastArmy
        -Turn turn
        -CombatHistory combatHistory

        +void setup()
        +void execute()
        +void createBeastsArmy()
        +void createHeroesArmy()
    }

    class Turn{
        -Army heroeArmy
        -Army beastArmy
        -int heroeAttack
        -int beastAttack
        -int damageDealt
        -CombatHistory combatHistory

        +Turn(Army heroeArmy, Army beastArmy, CombatHistory combatHistory)
        +void combat()
        +int calculateDamageDealt()
        +void showTurnResults(int currentTurn, Character heroe, Character beast)
    }

    class CombatHistory{
        -int turnNumber
        -Character winner
        -Character loser
        -int damage

        +CombatHistory(int turnNumber, Character winner, Character loser, int damage)
    }

    package characters{
        enum characterType{
            HUMAN
            ELF
            HOBBIT
            ORC
            GOBLIN
        }

        abstract class Character{
            #enum characterType
            -String name
            -int lifePoints
            -int shieldResistance

            +Character(String name, int lifePoints, int shieldResistance)
            +abstract boolean isHeroe()
            +abstract int attackOpponent(Character character)
            +abstract int defend(Character character)
            +abstract int throwDices()
            +abstract int getCharacterType()
        }

        package heroes{
            abstract class Heroe{
                +boolean isHeroe()
                +int throwDices()
                +abstract boolean fears(Character character)
                +abstract boolean hates(Character character)
                +abstract int attackOpponent(Character character)
                +abstract int defend(Character character)
                +abstract int getCharacterType()
            }

            class Human{            
                +int getCharacterType()
                +int attackOpponent(Character character)
                +int defend(Character character)
                +boolean fears(Character character)
                +boolean hates(Character character)
            }

            class Elf{
                +int getCharacterType()
                +int attackOpponent(Character character)
                +int defend(Character character)
                +boolean fears(Character character)
                +boolean hates(Character character)
            }

            class Hobbit{
                +int getCharacterType()
                +int attackOpponent(Character character)
                +int defend(Character character)
                +boolean fears(Character character)
                +boolean hates(Character character)
            }
        }

        package beasts{
            abstract class Beast{
                +boolean isHeroe()
                +int throwDices()
                +abstract boolean extraPower()
                +abstract int attackOpponent(Character character)
                +abstract int defend(Character character)
                +abstract int getCharacterType()
            }

            class Orc{
                +boolean extraPower()
                +int attackOpponent(Character character)
                +int defend(Character character)
                +int getCharacterType()
            }

            class Goblin{
                +boolean extraPower()
                +int attackOpponent(Character character)
                +int defend(Character character)
                +int getCharacterType()
            }
        }
    }

    class Army{
        -ArrayList<Character> army

        +Army()
        +ArrayList<Character> getArmy()
        +void setArmy(Character character)
    }

    abstract class AbstractCharacterFactory {
        Character createCharacter()
    }

    class HeroesFactory {
        +Heroe createCharacter()
    }

    class BeastsFactory {
        +Beast createCharacter()
    }
}

LordOfTheRings *-- Turn
LordOfTheRings *-- Army

Army *-- Character

Character <|-- Heroe
Character <|-- Beast

Heroe <|-- Human
Heroe <|-- Elf
Heroe <|-- Hobbit

Beast <|-- Orc
Beast <|-- Goblin

CombatHistory <-- Turn

LordOfTheRings ..> AbstractCharacterFactory
AbstractCharacterFactory <|-- HeroesFactory
AbstractCharacterFactory <|-- BeastsFactory

@enduml