@startuml

object LordOfTheRings

object characters
object heroes
object beasts
object army
object throwDices
object calculateDamageDealt
object combatHistory
object elf
object hobbit
object orc
object goblin
object human
object characterGoals
object attackOpponent

object gameGoals
object createHeroesArmy
object createBeastsArmy
object combat

object turns
object turnGoals

object lifePoints
object shieldResistance
object name

LordOfTheRings *-- turns
LordOfTheRings *-- army
LordOfTheRings o-- gameGoals

army *-- characters
turns --> army
characters <|-- heroes
characters <|-- beasts

gameGoals <|-- createHeroesArmy
gameGoals <|-- createBeastsArmy

turns o-- turnGoals
turnGoals <|-- combat
turnGoals <|-- throwDices
turnGoals <|-- calculateDamageDealt

characters *-- name
characters *-- lifePoints
characters *-- shieldResistance

turns --> combatHistory

heroes <|-- elf
heroes <|-- hobbit
beasts <|-- orc
beasts <|-- goblin
heroes <|-- human

characters o-- characterGoals
characterGoals <|-- attackOpponent 
@enduml